# Source: http://bulbapedia.bulbagarden.net/wiki/Type_chart#Generation_I

special = set(["water", "grass", "fire", "ice", "electric", "psychic", "dragon"])

super_effective = {"normal"     :   (),
                   "fighting"   :   ("normal", "rock", "ice"),
                   "flying"     :   ("fighting", "bug", "grass"),
                   "poison"     :   ("bug", "grass"),
                   "ground"     :   ("poison", "rock", "fire", "electric"),
                   "rock"       :   ("flying", "bug", "fire", "ice"),
                   "bug"        :   ("poison", "grass", "psychic"),
                   "ghost"      :   ("ghost", ),
                   "fire"       :   ("bug", "grass", "ice"),
                   "water"      :   ("ground", "rock", "fire"),
                   "grass"      :   ("ground", "rock", "water"),
                   "electric"   :   ("flying", "water"),
                   "psychic"    :   ("fighting", "poison"),
                   "ice"        :   ("flying", "ground", "grass", "dragon"),
                   "dragon"     :   ("dragon", )}
not_very_effective = {"normal"     :   ("rock", ),
                      "fighting"   :   ("flying", "poison", "bug", "psychic"),
                      "flying"     :   ("rock", "electric"),
                      "poison"     :   ("poison", "ground", "rock", "ghost"),
                      "ground"     :   ("bug", "grass"),
                      "rock"       :   ("fighting", "ground"),
                      "bug"        :   ("fighting", "flying", "ghost", "fire"),
                      "ghost"      :   (),
                      "fire"       :   ("rock", "fire", "water", "dragon"),
                      "water"      :   ("water", "grass", "dragon"),
                      "grass"      :   ("flying", "poison", "bug", "fire", "grass", "dragon"),
                      "electric"   :   ("grass", "electric", "dragon"),
                      "psychic"    :   ("psychic", ),
                      "ice"        :   ("water", "ice'"),
                      "dragon"     :   ()}
immune = {"normal"     :   ("ghost", ),
          "fighting"   :   ("ghost", ),
          "flying"     :   (),
          "poison"     :   (),
          "ground"     :   ("flying"),
          "rock"       :   (),
          "bug"        :   (),
          "ghost"      :   ("normal", "psychic"),
          "fire"       :   (),
          "water"      :   (),
          "grass"      :   (),
          "electric"   :   ("ground", ),
          "psychic"    :   (),
          "ice"        :   (),
          "dragon"     :   ()}
